version: "3.7"

services:
  wgtcrm-web:
    build: ./docker/nginx
    image: devmagellan/wgtcrm-web
    container_name: wgtcrm-web
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d:ro"
      - "./ap:/var/www/wgtcrm"
    depends_on:
      - "wgtcrm-php"
    networks:
      - wgtcrm

  wgtcrm-php:
    build: ./docker
    container_name: wgtcrm-php
    image: devmagellan/wgtcrm-php
    #environment:
      #APP_ENV: local
    restart: always
    working_dir: /var/www/wgtcrm
    volumes:
      - "./docker/php:/usr/local/etc/php:ro"
      - "./ap:/var/www/wgtcrm"
      #- ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wgtcrm
    secrets:
      - source: ssh_key
        target: /home/docker/.ssh/id_rsa

networks:
  wgtcrm:
    name: wgtcrm

secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
