version: 2.17
jobs:
  build:
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install gnupg2 pass
      - run: docker login --username=devmagellan --password=Sunimedia@1l
      - run: docker-compose build
      - run: docker push devmagellan/wgtcrm-php:latest
      - run: docker push devmagellan/wgtcrm-web:latest

        ##
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install sshpass
      - run:
          name: Deploy over SSH
          command: sshpass -p 'sunimedia' ssh -p 22 imediasun@3.18.112.158  "cd /var/www/lumen; docker pull devmagellan/wgtcrm-php:latest; docker pull devmagellan/wgtcrm-web:latest;";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
