version: 2.17
jobs:
  build:
    machine:
      enabled: true
    #working_directory: '~/'
    steps:
      - checkout
      - run: sudo apt update
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: sudo apt install gnupg2 pass
      - run: docker-compose build
      - run: docker login --username=devmagellan --password=Sunimedia@1l
      #- run: docker push devmagellan/wgtcrm-php:latest
      #- run: docker push devmagellan/wgtcrm-web:latest
      - run: docker-compose push devmagellan/wgt-compose

  ## ###
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install sshpass
      - run:
          name: Deploy over SSH
          command: sshpass -p 'sunimedia' scp ./docker-destroy-all.sh imediasun@3.18.112.158:/var/www/lumen; sshpass -p 'sunimedia' ssh -p 22 imediasun@3.18.112.158  "cd /var/www/lumen; chmod +x docker-destroy-all.sh ;./docker-destroy-all.sh;docker-compose pull devmagellan/wgt-compose:latest; ";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
